/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'position' : bigint,
}
export type MessageId = string;
export interface Picture {
  'id' : PictureId,
  'title' : string,
  'blob' : ExternalBlob,
  'description' : string,
  'position' : bigint,
}
export type PictureId = string;
export interface SweetTreat {
  'id' : TreatId,
  'name' : string,
  'description' : string,
  'position' : bigint,
}
export type TreatId = string;
export interface UnlockCount {
  'messages' : bigint,
  'treats' : bigint,
  'pictures' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMessage' : ActorMethod<[string, bigint], undefined>,
  'addPicture' : ActorMethod<[ExternalBlob, string, string], undefined>,
  'addSweetTreat' : ActorMethod<[string, string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMessage' : ActorMethod<[MessageId], undefined>,
  'deletePicture' : ActorMethod<[PictureId], undefined>,
  'deleteSweetTreat' : ActorMethod<[TreatId], undefined>,
  'getAllMessages' : ActorMethod<[], Array<Message>>,
  'getAllPictures' : ActorMethod<[], Array<Picture>>,
  'getAllTreats' : ActorMethod<[], Array<SweetTreat>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUnlockedMessages' : ActorMethod<[], Array<Message>>,
  'getUnlockedPictures' : ActorMethod<[], Array<Picture>>,
  'getUnlockedTreats' : ActorMethod<[], Array<SweetTreat>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementUnlocks' : ActorMethod<[boolean, boolean, boolean], UnlockCount>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderMessages' : ActorMethod<[Array<MessageId>], undefined>,
  'reorderPictures' : ActorMethod<[Array<PictureId>], undefined>,
  'reorderSweetTreats' : ActorMethod<[Array<TreatId>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMessage' : ActorMethod<[MessageId, string, bigint], undefined>,
  'updatePicture' : ActorMethod<
    [PictureId, ExternalBlob, string, string],
    undefined
  >,
  'updateSweetTreat' : ActorMethod<
    [TreatId, string, string, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];