/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageId = IDL.Text;
export const PictureId = IDL.Text;
export const TreatId = IDL.Text;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'position' : IDL.Nat,
});
export const Picture = IDL.Record({
  'id' : PictureId,
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'position' : IDL.Nat,
});
export const SweetTreat = IDL.Record({
  'id' : TreatId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'position' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const UnlockCount = IDL.Record({
  'messages' : IDL.Nat,
  'treats' : IDL.Nat,
  'pictures' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMessage' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addPicture' : IDL.Func([ExternalBlob, IDL.Text, IDL.Text], [], []),
  'addSweetTreat' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMessage' : IDL.Func([MessageId], [], []),
  'deletePicture' : IDL.Func([PictureId], [], []),
  'deleteSweetTreat' : IDL.Func([TreatId], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getAllPictures' : IDL.Func([], [IDL.Vec(Picture)], ['query']),
  'getAllTreats' : IDL.Func([], [IDL.Vec(SweetTreat)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUnlockedMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUnlockedPictures' : IDL.Func([], [IDL.Vec(Picture)], ['query']),
  'getUnlockedTreats' : IDL.Func([], [IDL.Vec(SweetTreat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementUnlocks' : IDL.Func(
      [IDL.Bool, IDL.Bool, IDL.Bool],
      [UnlockCount],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderMessages' : IDL.Func([IDL.Vec(MessageId)], [], []),
  'reorderPictures' : IDL.Func([IDL.Vec(PictureId)], [], []),
  'reorderSweetTreats' : IDL.Func([IDL.Vec(TreatId)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMessage' : IDL.Func([MessageId, IDL.Text, IDL.Nat], [], []),
  'updatePicture' : IDL.Func(
      [PictureId, ExternalBlob, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateSweetTreat' : IDL.Func([TreatId, IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageId = IDL.Text;
  const PictureId = IDL.Text;
  const TreatId = IDL.Text;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'position' : IDL.Nat,
  });
  const Picture = IDL.Record({
    'id' : PictureId,
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'position' : IDL.Nat,
  });
  const SweetTreat = IDL.Record({
    'id' : TreatId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'position' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const UnlockCount = IDL.Record({
    'messages' : IDL.Nat,
    'treats' : IDL.Nat,
    'pictures' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMessage' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addPicture' : IDL.Func([ExternalBlob, IDL.Text, IDL.Text], [], []),
    'addSweetTreat' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMessage' : IDL.Func([MessageId], [], []),
    'deletePicture' : IDL.Func([PictureId], [], []),
    'deleteSweetTreat' : IDL.Func([TreatId], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getAllPictures' : IDL.Func([], [IDL.Vec(Picture)], ['query']),
    'getAllTreats' : IDL.Func([], [IDL.Vec(SweetTreat)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUnlockedMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUnlockedPictures' : IDL.Func([], [IDL.Vec(Picture)], ['query']),
    'getUnlockedTreats' : IDL.Func([], [IDL.Vec(SweetTreat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementUnlocks' : IDL.Func(
        [IDL.Bool, IDL.Bool, IDL.Bool],
        [UnlockCount],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderMessages' : IDL.Func([IDL.Vec(MessageId)], [], []),
    'reorderPictures' : IDL.Func([IDL.Vec(PictureId)], [], []),
    'reorderSweetTreats' : IDL.Func([IDL.Vec(TreatId)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMessage' : IDL.Func([MessageId, IDL.Text, IDL.Nat], [], []),
    'updatePicture' : IDL.Func(
        [PictureId, ExternalBlob, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateSweetTreat' : IDL.Func(
        [TreatId, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };